-- Generated by tools/migrate-content.mjs — do not edit by hand.
-- Seeds events, albums, and photos from the salvaged Wix content.
-- Safe to re-run: every insert is keyed on a natural unique column.

begin;

-- Events ------------------------------------------------------------------
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2026-june-27th-guardians-night-at-the-ballpark-game', 'June 27th: Guardians Night at the Ballpark Game', 'Let''s join to cheer on the Cleveland Guardians vs Seattle Mariners. 7:10pm First pitch. Tanner Bibee City Connect Jersey give away.', 2026, 6, 27, 'f002fe_2ca2a89af5fb4aaca9b1bd62646efccb-mv2.jpg', 'Baseball match game flyer - Made with PosterMyWall')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2026-delta-chi-international-convention-craft-beer-tour', 'Delta Chi International Convention Craft Beer Tour', 'As the Brothers from the Northeast Ohio Alumni Chapter gather in Indy for the International Convention the Chapter will again be hosting it''s Convention Craft Beer tour on Friday July 24th afternoon. Stay turned for details and pricing.', 2026, 7, 24, 'f002fe_0b3c76e0e87a40fda01c09032ab31ede-mv2.jpg', 'Convention 2022 beer tour (1)')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2026-september-16th-rays-happy-hour', 'September 16th: Ray''s Happy Hour', 'As fall starts to set in. Join the Brothers as we head to the famous Ray''s Place in Kent, OH for our back to school annual Happy Hour', 2026, 9, 16, 'f002fe_7e84149bb2cc40deb4e60494bf17f840-mv2.jpg', 'Ray''s Happy Hour 2025')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2026-october-10th-delta-chi-northeast-ohio-alumni-chapter-10th-anniver', 'October 10th: Delta Chi Northeast Ohio Alumni Chapter 10th Anniversary Dinner', 'This Founders'' Day marks the 10th Anniversary for the Northeast Ohio Alumni Chapter. Join us as we celebrate all the years of fun and success of the Alumni Chapter over the years.', 2026, 10, 10, 'f002fe_60e3f89243c44532a84c473cf8de72ff-mv2.jpg', 'download (1)')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2026-october-13th-founders-day-traditions-with-kent-state', 'October 13th: Founders'' Day Traditions with Kent State', 'As we celebrate the Fraternity''s Founders'' Day. Members of the Chapter will travel to the Kent State Chapter to partake in the Chapter Traditions.', 2026, 10, 13, 'f002fe_27b447571f1e46ee8b7963bb3242cb8d-mv2.jpg', 'Founder Day Rock 2025')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2026-december-9th-holiday-get-together', 'December 9th: Holiday Get Together', 'The Holiday season is always a time to gather with friends and family. The Northeast Ohio Chapter will be gathering for our annual Holiday Get Together again this Holiday season.', 2026, 12, 9, 'f002fe_6d1468e78259436b8d3186703a405d21-mv2.jpg', 'istockphoto-507795393-612x612')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2026-may-28th-meet-and-greet-happy-hour', 'May 28th Meet and Greet Happy Hour', 'This May the Chapter hosted a happy hour to welcome new Brothers form the area to come out and see what the Chapter was about. We had the pleasure of reconnecting with a Case Western Alumnus, along with meeting two recent grads from the Ohio State Chapter. We hope to continue to see them along with more of the Northeast Ohio Alumni', 2026, 5, 28, 'f002fe_e647c773ba8b488aae1145d72eac5fce-mv2.jpg', 'Meet & Greet Happy Hour 2026_edited')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2025-dec-17th-holiday-get-together', 'Dec. 17th Holiday Get Together', 'The Chapter celebrated the holiday season again with our annual Holiday Get Together. Brothers participated in a white elephant gift exchange, while hanging out with undregrads from the Kent State Chapter along with Brothers from around the area.', 2025, 12, 17, 'f002fe_31425e00c7bb43fcad4f8351fbb6d9ee-mv2.jpeg', 'Holiday Get Together 2025')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2025-oct-13th-2025-founders-day-dinner', 'Oct. 13th 2025 Founders'' Day Dinner', 'We has a wonderful Founder''s Day Dinner with the Kent State Chapter undergrads. We elected our new officers and partake in the Kent State Founders Day Traditions. Painted the rock and enjoyed everyone''s company.', 2025, 10, 13, 'f002fe_de648f774a2b48ec9318da1a00776109-mv2.jpg', 'IMG_2086')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2025-sept-17th-2025-rays-place-happy-hour', 'Sept. 17th 2025 Ray''s Place Happy Hour', 'On Sept. 17th, 2025 The Alumni Chapter headed down to Ray''s in Kent OH for our 3rd annual Ray''s Happy hour to help support the Kent State Chapter Recruitment. We got to meet with the Chapter, enjoy conversations with Actives, AMs and Potential New Members and enjoy the company of all the local Alumni.', 2025, 9, 17, 'f002fe_7e84149bb2cc40deb4e60494bf17f840-mv2.jpg', 'Ray''s Happy Hour 2025')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2025-aug-9th-cleveland-whiskey-distillery-tour', 'Aug. 9th Cleveland Whiskey Distillery Tour', 'The Brothers got to experience a private tour of the distillery, while learning both the history of the company and newer historic building the company had moved into, we got to taste 4 amazing whiskey samplings. After the tour we were able to continue taste other amazing whiskeys. The event was fun and educational.', 2025, 8, 9, 'f002fe_67ed6e623e8c4d7797f2551f7abbad03-mv2.jpeg', 'image2')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2025-july-23rd-christmas-in-july-happy-hour', 'July 23rd Christmas in July Happy Hour', 'It''s time for our annual Christmas in July Happy Hour. The Brothers returned to the Wild Eagle Saloon for a night of food, fun and Brotherhood.', 2025, 7, 23, 'f002fe_b535a7f52be34066aaa9afbdbaf94826-mv2.jpg', 'X-mas in July')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2025-may-27th-guardians-vs-dodgers-night-at-the-ballpark', 'May 27th Guardians vs Dodgers Night at the Ballpark', 'The Brothers meet at the ballpark and watched the game from the Terrace Garden area. Though the Guardians didn''t bring home a winner the Brothers enjoyed the game and the brotherhood.', 2025, 5, 27, 'f002fe_9be01bf2ad6d48ea89cedd937e02016a-mv2.jpg', 'unnamed (1)')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2025-may-15th-2025-childrens-hunger-alliance-charity-event', 'May 15th 2025 Children''s Hunger Alliance Charity Event', 'On May 15th the Brothers once again joined the Children''s Hunger Alliance''s side by side charity dinner. Brothers supported CHA by attending the event. When enjoying dinner the Brothers listened to all the great support the CHA does for hunger children in the Cleveland Area.', 2025, 5, 15, 'f002fe_171263345076414aaf3cab341122b13d-mv2.jpg', 'IMG_1544')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2025-april-16th-bowling-kent-lanes', 'April 16th Bowling Kent Lanes', 'On April 2025 the Alumni Chapter joined the Kent State Undergrads for a night of Bowling and the Kent Lanes.', 2025, 4, 16, 'f002fe_34e4a914028840078a98df256125ee5b-mv2.jpeg', 'Bowling April 2025 (4)')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2025-march-1st-2025-kent-state-35th-5th-anniversary', 'March 1st 2025 Kent State 35th/5th Anniversary', 'On March 1st 2025 the Alumni Chapter had the pleasure of attending the Kent State Chapter 35th Anniversary event in Kent, Ohio. Our Chapter is proud to continue to support the local Chapters and be apart of this milestone event.', 2025, 3, 1, 'f002fe_18ee97c55e0344639cfea26ad6acecd8-mv2.jpg', 'KSU 35th Anniverary Mar 2025')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2025-feb-1st-2025-go-karting-and-axe-throwing', 'Feb 1st 2025 Go Karting and Axe Throwing', 'On Feb 1st 2025 the Alumni Chapter teamed up with the Case Western Chapter to help with Recruitment and have a wonderful event of indoor Go Karting and Axe Throwing. The Go karts reach up to 55mph and saw Dan Russell as the first winner of Alumni Go Karting.', 2025, 2, 1, 'f002fe_91a55be43c244be585c44e87d2859ab9-mv2.jpg', 'Go Karting Feb 2025 (1)')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2024-2024-annual-holiday-get-together', '2024 Annual Holiday Get Together', 'Another great Holiday Event. Alumni and Actives alike came together to celebrate the Holiday season at the Wild Eagle Saloon. The group exchanged white elephant gifts and showed the joys of Brotherhood.', 2024, null, null, 'f002fe_f29e26fda0984ba68cd2ef437100b5fa-mv2.jpg', 'Holiday Get Together 2024')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2024-brewdog-doghouse-brotherhood-getaway', 'BrewDog Doghouse Brotherhood Getaway', 'On Nov. 9th nine chapter members traveled to southeast Columbus to the Brewdog Brewhouse hotel for an overnight brotherhood. We got 1 suite and a few rooms and all hanging out with each other building on our already shared Brotherhood. We played classic video games, had dinner and took part in all the brewery had to offer. It was a great event to build our group together.', 2024, 11, 9, 'f002fe_b0d728c2183c4de28437b69f2982a71e-mv2.jpeg', 'brewdog')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2024-x-mas-in-july-happy-hour-2024', 'X-mas in July Happy Hour 2024', 'We had another great night of Brotherhood and we gathered at our favorite X-mas spot. Enjoyed catching up with old friends.', 2024, 7, null, 'f002fe_bad551914efb4228bb623039a09f8d56-mv2.jpg', 'X-mas in July Happy Hour 2024')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2024-guardians-vs-mariners-baseball-game', 'Guardians vs Mariners Baseball Game', 'Brothers and Families got out to the ballpark to celebrate Juneteeth and watch the Guardians take a win over the Mariners. Always a great time for the Brothers and their Families getting out to the ballpark', 2024, null, null, 'f002fe_0fe1ebf511814d9887d4d49744ca8b6b-mv2.jpg', 'Guardians game 2024')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2024-tog-golf-outing', 'Tog Golf Outing', 'Members of the Chapter gathered to swing some clubs and have fun at Top Golf on May 18th. Followed by lunch in the Area. What a great event to meet up and have some fun!', 2024, 5, 18, 'f002fe_fdcabaa6e950491e9a0bf621f3aeea04-mv2.jpg', 'Top Golf')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2024-2024-childrens-hunger-alliance-charity-event', '2024 Children''s Hunger Alliance Charity Event', 'The Alumni Chapter once again partnered up with our support of the Children''s Hunger Alliance in their fight for childhood hunger. Our Brothers donated items for auction and help raise money by attending their event in the flat on May 16th.', 2024, 5, 16, 'f002fe_3fe57ba045a242cfa3422721244b7c14-mv2.jpeg', 'Children''s Hunger Alliance May 2024')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2024-2024-v-foundation-headshot-fundrasier', '2024 V Foundation Headshot Fundrasier', 'The Alumni Chapter hosted 2 Photo sessions at both Kent State and Case Western, where of "C" Doug Tayek took headshot photos as we raised $300 for the V Foundation.', 2024, null, null, 'f002fe_46c0154a7fa34a7387ce52ac14138bfa-mv2.jpg', 'Professional Headshot')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2024-2024-great-lakes-brewery-hop-college', '2024 Great Lakes Brewery Hop College', 'This past March members of the Alumni Chapter experienced a 2 hour private Hop College event at the Great Lakes Brewery. The College went through the history of Craft Brewing and Great Lakes. We got a private tour of the Brewery and got to sample some of the great beer from Great Lakes.', 2024, 3, null, 'f002fe_eceb6b1c138f44b2be5ec2295d220fb9-mv2.jpg', 'Hop College')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2023-2023-annual-holiday-get-together', '2023 Annual Holiday Get Together', 'Again this year the Chapter got together to celebrate the holidays at the Wild Eagle Saloon. Some Brothers participated in a white elephant gift exchange with our "A" Michael Lippy getting a 3nd place cheerleader trophy as a gift. check out our pictures [here](https://dxneoalumni.wixsite.com/main/photo-gallery)', 2023, null, null, 'f002fe_38d0cdf0bcdf4489b4b26bb4850e235f-mv2.jpg', 'happy hour dec2023')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2023-2023-virtual-happy-hour', '2023 Virtual Happy Hour', 'To get our virtual Brothers involved we hosted a November Happy Hour Mid November. We challenged each other with Trivia and shared great tales from the undergraduate years.', 2023, 11, null, 'f002fe_3ec9bb04b2de4e14b358b9234ce650f5-mv2.jpg', 'virtual happy hour Nov 2023')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2023-2023-november-brewery-outing', '2023 November Brewery Outing', 'After some rescheduling the Alumni Chapter held a get together at the Collison Bend Brewery on the West side of the Flats in Cleveland. We had some new faces come out and join us.', 2023, 11, null, 'f002fe_1737e5e329674de2ac552e36ceaec87a-mv2.jpg', 'Collision Bend')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2023-2023-founders-day-dinner', '2023 Founders Day Dinner', 'The Chapter hosted 15 area Alumni and 6 undergrads from Kent State and Case Western at Bricco in Kent, OH to celebrate the 133th Founders Day.', 2023, null, null, 'f002fe_f8f41c8333f942a7a5ee0b774c3195a8-mv2.jpg', 'Founders Day 2023 (1)_edited')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2023-2023-summer-happy-hours', '2023 Summer Happy Hours', 'The 2023 was a wonderful 5 month events. We saw many different levels of attendance as we moved all around Northeast Ohio. It was a fun summer of great events. Tons of Brotherhood and connection.', 2023, null, null, 'f002fe_29ec927bf62f46a2960234ff0b874c5d-mv2.jpg', 'Summer Happy Hour 2023 Combined')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2023-guardians-vs-brewers-ballgame', 'Guardians vs. Brewers Ballgame', 'Brothers and there Families all came out to the Ballpark to watch our Cleveland Guardians beat the Milwaukee Brewers. Also got to take in a show from Walk the moon. See our [Gallery](https://dxneoalumni.wixsite.com/main/photo-gallery) for photos of all our events.', 2023, null, null, 'f002fe_bcf04d51db1041a6a40c00a721c9c025-mv2.jpg', 'Guardians game 2023 (1)')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2023-spring-alumni-rededication-ceremony', 'Spring Alumni Rededication Ceremony', 'This April we saw 2 more past Alumni go through the Delta Chi Alumni Rededication Ceremony at Kent State following the undergrad initiation. In our continued efforts to support our local Chapters. We held our 3rd Annual Night at the Ballpark to watch the Cleveland Indians take on the Chicago White Sox. This was a great night of fun with our Brothers from all over the area.', 2023, 4, null, 'f002fe_f3c0e30d1451404a89520b0b547b3f40-mv2.jpg', 'DXARC (1)')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2023-jan-21-2023-akron-food-bank', 'JAN. 21 2023 Akron Food Bank', '7 Members of the Chapter worked with the Akron-Canton Food Bank in Jan. Along with actives from the Kent State Chapter help with 21 hours of service helping sort meat. This Winter nearly 20 Brother got together to celebrate the holidays at the Wild Eagle Saloon in Broadview Hts. We shared an evening of Brotherhood and fun as we brought in the Holidays.', 2023, 1, 21, 'f002fe_f253a1f0faa649db9b7e0f2bedf98641-mv2.jpg', 'Food Bank')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2022-december-14-2022-holiday-get-together', 'December 14, 2022 Holiday Get Together', '', 2022, 12, 14, 'f002fe_5506899d1931478db196c81088bc0cc2-mv2.jpg', 'happy hour dec2022')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2022-oct-15-2022-founders-day-dinner', 'Oct. 15, 2022 Founders'' Day Dinner', 'The Brothers got together to Celebrate our Founders'' Day at R Shea Brewing in downtown Akron. See pictures in our [Photo Gallery.](https://dxneoalumni.wixsite.com/main/photo-gallery)', 2022, 10, 15, 'f002fe_a8f39bd27b3c4589a8ff994cc6042120-mv2.jpg', 'Founderday2022')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2021-october-30th-2021-akron-canton-beer-tour', 'October 30th, 2021 Akron/Canton Beer Tour', 'Eight Members toured on a Chartered bus to 7 local breweries in the Akron/Canton Area. The tour was a great success. See pictures in our [Photo Gallery.](https://dxneoalumni.wixsite.com/main/photo-gallery)', 2021, 10, 30, 'f002fe_bad42cd0bce4437bbf66953226a251d4-mv2.jpg', 'download (2)')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2019-dec-12th-2019-holiday-celebration-event', 'Dec. 12th, 2019 Holiday Celebration Event', 'The Alumni Chapter Hosted it''s 2nd Annual Holiday event at the Winking Lizard in Independence, OH', 2019, 12, 12, 'f002fe_a1fec78aa0a84835a4d489568912ec2a-mv2.jpg', 'Hoiliday dec2019')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2019-may-8th-2019-cleveland-indians-ballgame', 'May 8th, 2019 Cleveland Indians Ballgame', '', 2019, 5, 8, 'f002fe_de232716ac234be6b657488c602eb336-mv2_d_2016_1512_s_2.jpg', 'Cleveland Indians May 2019')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2019-alumni-rededication-ceremony', 'Alumni Rededication Ceremony', 'The Alumni Chapter hosted two Alumni Rededication Ceremonies at both Kent State and Case Western for Graduating Seniors. We welcomed 6 Brothers to this further and continuation of our Ritual.', 2019, null, null, 'f002fe_17dc1bb5ae274ee89826f49087caa6c9-mv2.jpg', 'Alumni Ceremony2')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2019-feb-15-17-2019-region-vi-regional-leader-conference-rlc', 'Feb. 15 - 17, 2019: Region VI Regional Leader Conference (RLC)', 'The Northeast Ohio Alumni Chapter had the pleasure to host the 2019 Region VI RLC. The RLC was held at the Glenmoor Country Club in Canton, OH with a Brotherhood event at the Pro Football Hall of Fame. This is the first time Delta Chi History that an Alumni Chapters has hosted. See pictures in our [Photo Gallery.](https://dxneoalumni.wixsite.com/main/photo-gallery)', 2019, 2, 15, 'f002fe_43c76dcde5f04c2184eb9140da5c5142-mv2.png', '')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2019-meet-and-greet-happy-hours', 'Meet and Greet Happy Hours', 'These were great events for Brothers to get together during the Holidays to hang out each other is a causal social event. See pictures in our [Photo Gallery.](https://dxneoalumni.wixsite.com/main/photo-gallery)', 2019, null, null, 'f002fe_be656c70722b417f965c472c90f24ac4-mv2.jpg', 'happy hour')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2018-may-1-2018-indians-vs-texas-ranger', 'May 1, 2018: Indians vs Texas Ranger', 'The Northeast Ohio Alumni Chapter hosted it''s second Night with the Indians. This was a great event seeing Alumni and undergrads from all over Northeast Ohio. See pictures in our [photo gallery](https://dxneoalumni.wixsite.com/main/photo-gallery)', 2018, 5, 1, 'f002fe_9f8d725c078f432890780a636125d8a8-mv2.png', '')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2017-october-13-2017-founders-day-dinner', 'October 13, 2017: Founder''s Day Dinner', 'Our 2nd annual Northeast Ohio all Chapter Founder Day Dinner. Sponsered by the Northeast Ohio Alumni Chapter, featuring the Case Western Chapter and Kent State Colony. This year''s event was at the Weymouth Country Club in Medina. See pictures in our [photo gallery](https://dxneoalumni.wixsite.com/main/photo-gallery)', 2017, 10, 13, 'f002fe_17c8d73f2c97434fb80b08c51d1e2f7b-mv2.jpg', '')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2017-may-16-2017-a-night-at-the-ballpark', 'May 16, 2017: A night at the ballpark', 'The Northeast Ohio Alumni Chapter sponsored a night to see your 2016 American League Champion Cleveland Indians take on the Tampa Bay Rays at Progressive Field. The event saw Alumni from five different Chapters and their families, came out to meet and enjoy Brotherhood!! See pictures in our [photo gallery](https://dxneoalumni.wixsite.com/main/photo-gallery)', 2017, 5, 16, 'f002fe_5a8dec596a4c4c38846734f13fb01134-mv2.jpg', '')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;
insert into public.events (slug, title, description, year, month, day, image_file, image_alt) values ('2016-october-13-2016-founders-day-dinner', 'October 13, 2016: Founder''s Day Dinner', 'The Northeast Ohio Alumni Chapter, co-sponsored with the Case Western Reserve Chapter a celebration of our Founder''s Day with a Dinner at Harry''s Steakhouse in Independence, OH. This event mark the reformation of the Northeast Ohio Alumni Chapter. See pictures in our [photo gallery](https://dxneoalumni.wixsite.com/main/photo-gallery)', 2016, 10, 13, 'f002fe_0c634f0595424520b5b294d64067f183-mv2.jpg', '')
on conflict (slug) do update set title = excluded.title, description = excluded.description, year = excluded.year, month = excluded.month, day = excluded.day, image_file = excluded.image_file, image_alt = excluded.image_alt;

-- Albums ------------------------------------------------------------------
insert into public.albums (slug, title, event_id, year, month) values ('meet-greet-happy-hour-2026', 'Meet & Greet Happy Hour 2026', (select id from public.events where slug = '2026-may-28th-meet-and-greet-happy-hour'), 2026, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('holiday-get-together-2025', 'Holiday Get Together 2025', (select id from public.events where slug = '2025-dec-17th-holiday-get-together'), 2025, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('founders-day-dinner-2025', 'Founders Day Dinner 2025', (select id from public.events where slug = '2025-oct-13th-2025-founders-day-dinner'), 2025, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('founder-day-rock-2025', 'Founder Day Rock 2025', (select id from public.events where slug = '2026-october-13th-founders-day-traditions-with-kent-state'), 2025, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('ray-s-happy-hour-2025', 'Ray''s Happy Hour 2025', (select id from public.events where slug = '2026-september-16th-rays-happy-hour'), 2025, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('cleveland-whiskey-tour', 'Cleveland Whiskey Tour', (select id from public.events where slug = '2025-aug-9th-cleveland-whiskey-distillery-tour'), 2025, 8)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('childrens-hunger-alliance-may-2025', 'Childrens Hunger Alliance May 2025', null, 2025, 5)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('bowling-april-2025', 'Bowling April 2025', (select id from public.events where slug = '2025-april-16th-bowling-kent-lanes'), 2025, 4)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('ksu-35th-anniverary-mar-2025', 'KSU 35th Anniverary Mar 2025', (select id from public.events where slug = '2025-march-1st-2025-kent-state-35th-5th-anniversary'), 2025, 3)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('neo-ksu-35th-anniverary-mar-2025', 'NEO KSU 35th Anniverary Mar 2025', null, 2025, 3)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('go-karting-feb-2025', 'Go Karting Feb 2025', (select id from public.events where slug = '2025-feb-1st-2025-go-karting-and-axe-throwing'), 2025, 2)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('holiday-get-together-2024', 'Holiday Get Together 2024', (select id from public.events where slug = '2024-2024-annual-holiday-get-together'), 2024, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('brewdog-brewhouse-nov-2024', 'Brewdog Brewhouse Nov 2024', null, 2024, 11)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('founders-day-2024', 'Founders Day 2024', null, 2024, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('kent-happy-hour-sept-2024', 'Kent Happy Hour Sept 2024', null, 2024, 9)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('convention-2024', 'Convention 2024', null, 2024, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('convention-beer-tour-2024', 'Convention Beer Tour 2024', null, 2024, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('x-mas-in-july-happy-hour-2024', 'X-mas in July Happy Hour 2024', (select id from public.events where slug = '2024-x-mas-in-july-happy-hour-2024'), 2024, 7)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('guardians-game-2024', 'Guardians Game 2024', (select id from public.events where slug = '2024-guardians-vs-mariners-baseball-game'), 2024, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('top-golf-2024', 'Top Golf 2024', null, 2024, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('children-s-hunger-alliance-may-2024', 'Children''s Hunger Alliance May 2024', (select id from public.events where slug = '2024-2024-childrens-hunger-alliance-charity-event'), 2024, 5)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('v-foundation-2024', 'V Foundation 2024', (select id from public.events where slug = '2024-2024-v-foundation-headshot-fundrasier'), 2024, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('great-lakes-hop-college-march-2024', 'Great Lakes Hop College March 2024', (select id from public.events where slug = '2024-2024-great-lakes-brewery-hop-college'), 2024, 3)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('feb-2024-happy-hour', 'Feb 2024 Happy Hour', null, 2024, 2)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('holiday-get-together-2023', 'Holiday Get Together 2023', (select id from public.events where slug = '2023-2023-annual-holiday-get-together'), 2023, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('nov-brewery-get-together-2023', 'Nov. Brewery Get Together 2023', null, 2023, 11)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('founders-day-2023', 'Founders Day 2023', (select id from public.events where slug = '2023-2023-founders-day-dinner'), 2023, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('summer-happy-hour-sept-2023', 'Summer Happy Hour Sept 2023', null, 2023, 9)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('summer-happy-hour-aug-2023', 'Summer Happy Hour Aug 2023', null, 2023, 8)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('cleveland-guardians-2-june-2023', 'Cleveland Guardians (2) June 2023', null, 2023, 6)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('summer-happy-hour-june-2023', 'Summer Happy Hour June 2023', null, 2023, 6)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('summer-happy-hour-may-2023', 'Summer Happy Hour May 2023', null, 2023, 5)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('food-bank', 'Food Bank', (select id from public.events where slug = '2023-jan-21-2023-akron-food-bank'), 2023, 1)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('holiday-get-together-2022', 'Holiday Get Together 2022', (select id from public.events where slug = '2022-december-14-2022-holiday-get-together'), 2022, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('founders-day-2022', 'Founders Day 2022', (select id from public.events where slug = '2022-oct-15-2022-founders-day-dinner'), 2022, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('summer-happy-hour-3-2022', 'Summer Happy Hour 3 2022', null, 2022, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('childern-hunger-alliance-2022', 'Childern Hunger Alliance 2022', null, 2022, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('convention-2022-beer-tour', 'Convention 2022 beer tour', (select id from public.events where slug = '2026-delta-chi-international-convention-craft-beer-tour'), 2022, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('convention-2022', 'Convention 2022', null, 2022, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('summer-happy-hour-2-2022', 'Summer Happy Hour 2 2022', null, 2022, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('brewery-tour-2021', 'Brewery Tour 2021', null, 2021, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('virtual-happy-hour-april-2020', 'Virtual Happy Hour April 2020', null, 2020, 4)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('founders-day-2019', 'Founders day 2019', null, 2019, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('cleveland-indians-may-2019', 'Cleveland Indians May 2019', (select id from public.events where slug = '2019-may-8th-2019-cleveland-indians-ballgame'), 2019, 5)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('rlc-2019', 'RLC 2019', (select id from public.events where slug = '2019-feb-15-17-2019-region-vi-regional-leader-conference-rlc'), 2019, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('happy-hour-dec-2018', 'Happy Hour Dec 2018', null, 2018, 12)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('happy-hour-nov-2018', 'Happy Hour Nov 2018', null, 2018, 11)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('founder-s-day-2018', 'Founder''s Day 2018', null, 2018, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('cleveland-indians-may-2018', 'Cleveland Indians May 2018', null, 2018, 5)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('founders-day-2017', 'Founders Day 2017', null, 2017, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('cleveland-indians-may-2017', 'Cleveland Indians May 2017', null, 2017, 5)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('founders-dinner-chapter-founders-2016', 'Founders dinner Chapter founders 2016', null, 2016, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;
insert into public.albums (slug, title, event_id, year, month) values ('founders-day-2016', 'Founders day 2016', null, 2016, null)
on conflict (slug) do update set title = excluded.title, event_id = excluded.event_id, year = excluded.year, month = excluded.month;

-- Photos ------------------------------------------------------------------
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'meet-greet-happy-hour-2026'), 'f002fe_e7a1125d696b4a8d888c265f69bf4260-mv2.jpeg', 'Meet & Greet Happy Hour 2026', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'holiday-get-together-2025'), 'f002fe_31425e00c7bb43fcad4f8351fbb6d9ee-mv2.jpeg', 'Holiday Get Together 2025', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-dinner-2025'), 'f002fe_0b148015c80647efa28c612ff89ad811-mv2.jpg', 'Founders Day Dinner 2025', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founder-day-rock-2025'), 'f002fe_27b447571f1e46ee8b7963bb3242cb8d-mv2.jpg', 'Founder Day Rock 2025', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'ray-s-happy-hour-2025'), 'f002fe_7e84149bb2cc40deb4e60494bf17f840-mv2.jpg', 'Ray''s Happy Hour 2025', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-whiskey-tour'), 'f002fe_91deeac25f5148cd88b03f96ebd67aea-mv2.jpeg', 'Cleveland Whiskey Tour (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-whiskey-tour'), 'f002fe_1ef4e2cd3f0749efa6422f8c712ec8d5-mv2.jpeg', 'Cleveland Whiskey Tour (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-whiskey-tour'), 'f002fe_f85de6b228564722898d41022cb73c2c-mv2.jpg', 'Cleveland Whiskey Tour (3)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-whiskey-tour'), 'f002fe_a667ad8d09b944a59bb6c8ea6982cbc0-mv2.jpg', 'Cleveland Whiskey Tour (4)', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-whiskey-tour'), 'f002fe_df21f82f84364fbb95dc8b965b6ac208-mv2.jpg', 'Cleveland Whiskey Tour (5)', 4)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'childrens-hunger-alliance-may-2025'), 'f002fe_0972b025d2654304962d23f004f708d5-mv2.jpg', 'Childrens Hunger Alliance May 2025', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'bowling-april-2025'), 'f002fe_c62d8ce66f834b35873c59bb54c4eec0-mv2.jpeg', 'Bowling April 2025 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'bowling-april-2025'), 'f002fe_1b87191390e8410c9e585db4d5a0ac6c-mv2.jpeg', 'Bowling April 2025 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'bowling-april-2025'), 'f002fe_3a41b394405e489d98127e3a75b35bc1-mv2.jpeg', 'Bowling April 2025 (3)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'bowling-april-2025'), 'f002fe_34e4a914028840078a98df256125ee5b-mv2.jpeg', 'Bowling April 2025 (4)', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'ksu-35th-anniverary-mar-2025'), 'f002fe_18ee97c55e0344639cfea26ad6acecd8-mv2.jpg', 'KSU 35th Anniverary Mar 2025', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'neo-ksu-35th-anniverary-mar-2025'), 'f002fe_26f36972400b449a9c1a1026158f5fe7-mv2.jpg', 'NEO KSU 35th Anniverary Mar 2025', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'go-karting-feb-2025'), 'f002fe_91a55be43c244be585c44e87d2859ab9-mv2.jpg', 'Go Karting Feb 2025 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'go-karting-feb-2025'), 'f002fe_0df574dab110430bb64df55d2cbb6fcd-mv2.jpg', 'Go Karting Feb 2025 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'go-karting-feb-2025'), 'f002fe_2c2f6546a642473a853f169f95b2a147-mv2.jpg', 'Go Karting Feb 2025 (3)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'go-karting-feb-2025'), 'f002fe_ed928125af6a460ba0fdc66dcaa53bf8-mv2.jpg', 'Go Karting Feb 2025 (4)', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'go-karting-feb-2025'), 'f002fe_3ccbf1be991c45ffb21db7062de36d2b-mv2.jpg', 'Go Karting Feb 2025 (5)', 4)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'go-karting-feb-2025'), 'f002fe_7947e918762b4a9799b4fae146332024-mv2.jpg', 'Go Karting Feb 2025 (6)', 5)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'holiday-get-together-2024'), 'f002fe_f29e26fda0984ba68cd2ef437100b5fa-mv2.jpg', 'Holiday Get Together 2024', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'brewdog-brewhouse-nov-2024'), 'f002fe_b981f1152e7d4864af6675ef9b7612a9-mv2.jpg', 'Brewdog Brewhouse Nov 2024 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'brewdog-brewhouse-nov-2024'), 'f002fe_de25c155fd9e4c8d93e6bc4f52fac2b7-mv2.jpg', 'Brewdog Brewhouse Nov 2024 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2024'), 'f002fe_dfea92b6c0b241d48d387b8c4c941785-mv2.jpg', 'Founders Day 2024 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2024'), 'f002fe_70c15c328e71497ba125821d0fd57ae3-mv2.jpg', 'Founders Day 2024 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2024'), 'f002fe_90f6058807794d34a1eeda338fb959f8-mv2.jpg', 'Founders Day 2024 (3)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2024'), 'f002fe_59d3cf242a524d9282afd01a12363a27-mv2.jpg', 'Founders Day 2024 (4)', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'kent-happy-hour-sept-2024'), 'f002fe_0a5a9eadfa5946e4b9a4cbf177406459-mv2.jpg', 'Kent Happy Hour Sept 2024', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'convention-2024'), 'f002fe_19d15156f8c4461fa706c2350c3387c5-mv2.jpg', 'Convention 2024 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'convention-2024'), 'f002fe_bbd0c04c915c4ff5af9e760a37d12921-mv2.jpg', 'Convention 2024 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'convention-2024'), 'f002fe_bfb4b4b0fb4f4f67bb9f6b8d8a2d02b2-mv2.jpg', 'Convention 2024 (3)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'convention-2024'), 'f002fe_65fe9cea6ec24ef6b4ec2d9797a9950f-mv2.jpg', 'Convention 2024 (4)', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'convention-beer-tour-2024'), 'f002fe_0688351cbb034adfbeb831279fbf488f-mv2.jpg', 'Convention Beer Tour 2024 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'convention-beer-tour-2024'), 'f002fe_0ee8f91203f449a084877c42088a7275-mv2.jpg', 'Convention Beer Tour 2024 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'convention-beer-tour-2024'), 'f002fe_194a27bab1d040ce8172185c302d93f5-mv2.jpg', 'Convention Beer Tour 2024 (3)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'x-mas-in-july-happy-hour-2024'), 'f002fe_bad551914efb4228bb623039a09f8d56-mv2.jpg', 'X-mas in July Happy Hour 2024', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'guardians-game-2024'), 'f002fe_bcc5c397df524afc9db17bd8dd6b8929-mv2.jpg', 'Guardians Game 2024 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'guardians-game-2024'), 'f002fe_2f4bdf8375c843218b8183cde66faba2-mv2.jpg', 'Guardians Game 2024 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'top-golf-2024'), 'f002fe_3ddf7de21829481686cfc882889bc3d2-mv2.jpg', 'Top Golf 2024 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'top-golf-2024'), 'f002fe_02a4673747e34207a3f4ad64bbedacfb-mv2.jpg', 'Top Golf 2024 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'top-golf-2024'), 'f002fe_c13baefb41ba4322abb6a61affac395f-mv2.jpeg', 'Top Golf 2024 (3)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'top-golf-2024'), 'f002fe_45c65bc5331042f49e6997348e8f6f06-mv2.jpeg', 'Top Golf 2024 (4)', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'top-golf-2024'), 'f002fe_6a7c9d755e884db1a8d9cec3468f7a80-mv2.jpeg', 'Top Golf 2024 (5)', 4)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'top-golf-2024'), 'f002fe_640c896b7e4c4e06893e93f10f27465f-mv2.jpeg', 'Top Golf 2024 (6)', 5)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'top-golf-2024'), 'f002fe_282e5b0cb8ea402398e2f332fc2b5892-mv2.jpeg', 'Top Golf 2024 (7)', 6)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'children-s-hunger-alliance-may-2024'), 'f002fe_3fe57ba045a242cfa3422721244b7c14-mv2.jpeg', 'Children''s Hunger Alliance May 2024', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'v-foundation-2024'), 'f002fe_c41792680d104053bb0907415733514e-mv2.jpg', 'V Foundation 2024 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'v-foundation-2024'), 'f002fe_77959c49c0d34fc388a763ddfc61891d-mv2.jpg', 'V Foundation 2024 (3)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'v-foundation-2024'), 'f002fe_eadcd00c35b849c181bb8038a059bb52-mv2.jpg', 'V Foundation  2024 (4)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'great-lakes-hop-college-march-2024'), 'f002fe_303e83fedf3344bd814d31e8a0c0e654-mv2.jpeg', 'Great Lakes Hop College March 2024 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'great-lakes-hop-college-march-2024'), 'f002fe_f2b07186c01b4fa5a4391a87b3cacd1e-mv2.jpeg', 'Great Lakes Hop College March 2024 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'great-lakes-hop-college-march-2024'), 'f002fe_b74404903e0843d6adce5917388feac6-mv2.jpeg', 'Great Lakes Hop College March 2024 (3)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'feb-2024-happy-hour'), 'f002fe_a89ef63e00924c0fa3b50bfe20552846-mv2.jpeg', 'Feb 2024 Happy Hour', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'holiday-get-together-2023'), 'f002fe_5c7d91dd52e24eccaa342e2ef98c9103-mv2.jpg', 'Holiday Get Together 2023', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'nov-brewery-get-together-2023'), 'f002fe_bf6facdb9cde4a0696d9e511502e4ee9-mv2.jpg', 'Nov. Brewery Get Together 2023', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2023'), 'f002fe_6eedb8d32d414064a0a41c35f1b7c0a5-mv2.jpeg', 'Founders Day 2023 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2023'), 'f002fe_db1f81f8bc62428b8cf80c49465c1dba-mv2.jpg', 'Founders Day 2023 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2023'), 'f002fe_eb2c83dd37424d129a85ad713d9c9a59-mv2.jpg', 'Founders Day 2023 (3)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2023'), 'f002fe_fec1cd29ed1a4890a960bee734dede1b-mv2.jpg', 'Founders Day 2023 (4)', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2023'), 'f002fe_5d15cd15df8e48069f2bc9149b04e897-mv2.jpg', 'Founders Day 2023 (5)', 4)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'summer-happy-hour-sept-2023'), 'f002fe_778577136346413dbd68c7a2f1a6cf24-mv2.jpg', 'Summer Happy Hour Sept 2023', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'summer-happy-hour-aug-2023'), 'f002fe_4a57a1a7c4b54f65bfc25cec9861f143-mv2.jpg', 'Summer Happy Hour Aug 2023', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-guardians-2-june-2023'), 'f002fe_92da10afb3b94db29b9e77ceaf20ced9-mv2.jpg', 'Cleveland Guardians (2) June 2023', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'summer-happy-hour-june-2023'), 'f002fe_97886931050545d3a9c4071c3d66c0d4-mv2.jpg', 'Summer Happy Hour June 2023', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'summer-happy-hour-may-2023'), 'f002fe_84fc8bd1ffba483cbc704cbba786d8c8-mv2.jpg', 'Summer Happy Hour May 2023', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'food-bank'), 'f002fe_93a9cafed0ff4fecbe5a7c22f8cd6db3-mv2.jpg', 'Food Bank 1', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'food-bank'), 'f002fe_a62c0d13ad1e49838338932df4ed26d8-mv2.jpg', 'Food Bank 2', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'food-bank'), 'f002fe_f36261a7b37443fca8c85f0432981ef3-mv2.jpg', 'Food Bank 3', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'food-bank'), 'f002fe_2c4ff10d358244d5bb7dc1bdf77aaa73-mv2.jpg', 'Food Bank 4', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'food-bank'), 'f002fe_718311c25ce442be86a9c0392a7c2d44-mv2.jpg', 'Food Bank 5', 4)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'food-bank'), 'f002fe_6dc4380aca7b49329acd26f2c04b4d80-mv2.jpg', 'Food Bank 6', 5)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'food-bank'), 'f002fe_1f54a67df00147c38647a137b8729e7c-mv2.jpg', 'Food bank 7', 6)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'food-bank'), 'f002fe_42aabc8cb0d84c4eb7637bbdc24934ea-mv2.jpg', 'Food Bank 8', 7)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'food-bank'), 'f002fe_36f833ffa0654c5087cbecf3797240a2-mv2.jpg', 'Food Bank 9', 8)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'food-bank'), 'f002fe_cfedde598c2e41ef8c463bd99e598522-mv2.jpg', 'Food Bank 11', 9)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'holiday-get-together-2022'), 'f002fe_e465d3fe15ae453d9357dc52c677af1e-mv2.jpg', 'Holiday Get Together 2022', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2022'), 'f002fe_959a07c234aa43c0a553e331ad4c65ed-mv2.jpg', 'Founders Day 2022 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2022'), 'f002fe_24b7eb732a7446528739bb35c7ae0c0f-mv2.jpg', 'Founders Day 2022 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2022'), 'f002fe_9750684815a44dce9e00a211b72c6a2a-mv2.jpg', 'Founders Day 2022 (3)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2022'), 'f002fe_84f3a6b7e98c4c1b9692a3dbfb568834-mv2.jpg', 'Founders Day 2022 (4)', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'summer-happy-hour-3-2022'), 'f002fe_46fb8e4f48b44225b74f566546762240-mv2.jpg', 'Summer Happy Hour 3 2022', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'childern-hunger-alliance-2022'), 'f002fe_30cf02c37f0c4edebbb743a5de13dedd-mv2.jpg', 'Childern Hunger Alliance 2022', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'convention-2022-beer-tour'), 'f002fe_0b3c76e0e87a40fda01c09032ab31ede-mv2.jpg', 'Convention 2022 beer tour (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'convention-2022-beer-tour'), 'f002fe_464a1e31fafe497a9fdff4d43cdf42ee-mv2.jpg', 'Convention 2022 beer tour (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'convention-2022'), 'f002fe_015ace6ff3144a5f90f773c46e35fd9f-mv2.jpeg', 'Convention 2022 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'convention-2022'), 'f002fe_05c57da0f2b84b9c931f1e30f6cf6e8c-mv2.jpg', 'Convention 2022 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'convention-2022'), 'f002fe_207f24d7f874488db31e44af87d95a11-mv2.jpg', 'Convention 2022 (3)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'convention-2022'), 'f002fe_236807d07b83467e94eff9a9c4bb1709-mv2.jpg', 'Convention 2022 (4)', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'summer-happy-hour-2-2022'), 'f002fe_4b587bbb84a6453c9a8ed4c38e7f1147-mv2.jpg', 'Summer Happy Hour 2 2022', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'brewery-tour-2021'), 'f002fe_e297f071bf0e489cbe1de328f9982800-mv2.jpg', 'Brewery Tour 2021 1', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'brewery-tour-2021'), 'f002fe_10fed0cc51594e6fb4e10a390ee6a35b-mv2.jpg', 'Brewery Tour 2021 2', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'brewery-tour-2021'), 'f002fe_b8eef8502bb2492e9581bd2ca8fe5284-mv2.jpg', 'Brewery Tour 2021 3', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'brewery-tour-2021'), 'f002fe_7a3706acfa2648429b36dc0b700397a2-mv2.jpg', 'Brewery Tour 2021 4', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'brewery-tour-2021'), 'f002fe_03b0beff33754dca87dc0a0443f01d81-mv2.jpg', 'Brewery Tour 2021 5', 4)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'brewery-tour-2021'), 'f002fe_c8e6d7fd78f84c808b7a9bc1635085d2-mv2.jpg', 'Brewery Tour 2021 6', 5)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'brewery-tour-2021'), 'f002fe_db4d9ee9592f47de85f8d2cf5834f81f-mv2.jpg', 'Brewery Tour 2021 7', 6)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'brewery-tour-2021'), 'f002fe_307baa357a8742bc8ed1ffda7abe5fe4-mv2.jpg', 'Brewery Tour 2021 8', 7)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'virtual-happy-hour-april-2020'), 'f002fe_29a6b51ec9e742df8ff24d4f4a04bdc8-mv2.jpg', 'Virtual Happy Hour April 2020', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2019'), 'f002fe_24265f9629074b8eab9f58ca84e345d3-mv2_d_4032_3024_s_4_2.jpg', 'Founders day 2019_1', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2019'), 'f002fe_897a70e9ed684d428f9d1c3324247dff-mv2_d_3024_4032_s_4_2.jpg', 'Founders Day 2019_2', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2019'), 'f002fe_75ee9f3cb07443e2a3a718fa746d0673-mv2_d_4032_3024_s_4_2.jpg', 'Founders Day 2019_3', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2019'), 'f002fe_0872f773655c4ac7836765f6d07bdda7-mv2_d_3024_4032_s_4_2.jpg', 'Founders Day 2019_4', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2019'), 'f002fe_156f2db528964cfbb7078991a165efaa-mv2_d_3264_2448_s_4_2.jpg', 'Founders Day 2019_5', 4)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2019'), 'f002fe_901c4d631ee843168d3a4d0c294ec11d-mv2_d_3264_2448_s_4_2.jpg', 'Founders Day 2019_6', 5)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-indians-may-2019'), 'f002fe_de232716ac234be6b657488c602eb336-mv2_d_2016_1512_s_2.jpg', 'Cleveland Indians May 2019', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'rlc-2019'), 'f002fe_4e30e74840c04f55aac971f6b3124eb8-mv2_d_2016_1512_s_2.jpg', 'RLC 2019', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'rlc-2019'), 'f002fe_8914591e51c948f496dc129b859cd7ad-mv2_d_2016_1512_s_2.jpg', 'RLC 2019_3', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'happy-hour-dec-2018'), 'f002fe_f24138f12f5e4a9d9fff20ef3f72b1da-mv2_d_2016_1512_s_2.jpg', 'Happy Hour Dec 2018', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'happy-hour-dec-2018'), 'f002fe_d283037f586546ad932138cf89df0d47-mv2_d_2016_1512_s_2.jpg', 'Happy Hour Dec 2018_2', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'happy-hour-dec-2018'), 'f002fe_53ea833aa4094e6cb3998eab2a29c464-mv2_d_2016_1512_s_2.jpg', 'Happy Hour Dec 2018_3', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'happy-hour-dec-2018'), 'f002fe_018e9473aaa849e69aa7694bf024833b-mv2_d_2016_1512_s_2.jpg', 'Happy Hour Dec 2018_4', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'happy-hour-nov-2018'), 'f002fe_54d7aaf92bb0480db0e1acb71c101a2e-mv2_d_2016_1512_s_2.jpg', 'Happy Hour Nov 2018', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founder-s-day-2018'), 'f002fe_c262bbc4f5e7468e8979c0c360355201-mv2_d_4032_3024_s_4_2.jpg', 'Founder''s Day 2018', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-indians-may-2018'), 'f002fe_30de6d21b6624eb9a87e63b0b6a44f57-mv2_d_2016_1512_s_2.jpg', 'Cleveland Indians May 2018 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-indians-may-2018'), 'f002fe_1eb05c06040a4c2c9a100ab3776503ec-mv2_d_2016_1512_s_2.jpg', 'Cleveland Indians May 2018 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-indians-may-2018'), 'f002fe_7d13dfb4dc0a40a6978f895c3f6c8661-mv2_d_2016_1512_s_2.jpg', 'Cleveland Indians May 2018 (3)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-indians-may-2018'), 'f002fe_954d4db8e6bf43158ae38f5bce523d03-mv2_d_2016_1512_s_2.jpg', 'Cleveland Indians May 2018 (4)', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-indians-may-2018'), 'f002fe_f2b9ec771a99478b9d07c5f87a0e94f5-mv2_d_2016_1512_s_2.jpg', 'Cleveland Indians May 2018 (5)', 4)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2017'), 'f002fe_6d6bce11ea5742caba7010572a7bc121-mv2.jpg', 'Founders Day 2017 (2)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2017'), 'f002fe_13e6412b1d9c4744b8d91e7b276e7cc6-mv2.jpg', 'Founders Day 2017 (3)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2017'), 'f002fe_147315d3d2c44b24a5f88633bfcf8688-mv2.jpg', 'Founders Day 2017 (4)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2017'), 'f002fe_23b2516c86874158aa650050c3d978c7-mv2.jpg', 'Founders Day 2017 (5)', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-indians-may-2017'), 'f002fe_23f1b68d73d845c78ac29c326f2917ff-mv2.jpg', 'Cleveland Indians May 2017 (1)', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-indians-may-2017'), 'f002fe_76f4cf9079ab49bcb7a7bd906a550209-mv2.jpg', 'Cleveland Indians May 2017 (2)', 1)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-indians-may-2017'), 'f002fe_c2f6ab32a5724fecaedecddd4f527e23-mv2.jpg', 'Cleveland Indians May 2017 (3)', 2)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-indians-may-2017'), 'f002fe_d7fb61d27ff5409a852289f86e1b6c10-mv2.jpg', 'Cleveland Indians May 2017 (4)', 3)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-indians-may-2017'), 'f002fe_71c911c3090440cdaf2de8c019ce4c61-mv2.jpg', 'Cleveland Indians May 2017 (5)', 4)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'cleveland-indians-may-2017'), 'f002fe_b99fbde483374e4e9bfcc2747a08c253-mv2.jpg', 'Cleveland Indians May 2017 (6)', 5)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-dinner-chapter-founders-2016'), 'f002fe_6cc2358307c3457b8de502da8caeeaf9-mv2.jpg', 'Founders dinner Chapter founders 2016', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;
insert into public.photos (album_id, file, caption, sort_order) values ((select id from public.albums where slug = 'founders-day-2016'), 'f002fe_e768b0c09df94169a4aed93d2a4bc8e4-mv2.jpg', 'Founders day 2016', 0)
on conflict (file) do update set caption = excluded.caption, sort_order = excluded.sort_order;

commit;
